name: echo call from library
on:
  workflow_call:

jobs:
  build-flow:
    runs-on: ubuntu-latest
    steps:
      - name: echoing from library
        run: |
              echo "helloo from library"
